### ISSUE TITLE
Issue when reading color-scheme key

### ISSUE THREAD

**Issue by edfloreshz** [bilelmoussaoui/ashpd#106]
I'm getting the following error when trying to use the `color_scheme()` method or trying to read it directly with the `read()` method.

`Error: ZBus Error: incorrect type`

```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let connection = ashpd::zbus::Connection::session().await?;
    let proxy = ashpd::desktop::settings::SettingsProxy::new(&connection).await?;
    let color_scheme = proxy.color_scheme().await?;
    match color_scheme {
        ashpd::desktop::settings::ColorScheme::PreferDark => println!("Dark"),
        ashpd::desktop::settings::ColorScheme::PreferLight => println!("Light"),
        ashpd::desktop::settings::ColorScheme::NoPreference => println!("Default"),
    };
    Ok(())
}
```

I'm able to get the key using `qdbus`
```bash
qdbus org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read "org.freedesktop.appearance" "color-scheme"

Output: 1
```

## Backtrace
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Zbus(Variant(IncorrectType))', examples/color_scheme.rs:5:51
stack backtrace:
   0:     0x55bd3181d350 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55bd3181d350 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bd3181d350 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55bd3181d350 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55bd3183d60e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x55bd31818155 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x55bd3181d115 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55bd3181d115 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55bd3181e9cf - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x55bd3181e70a - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x55bd3181f0c8 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x55bd3181ee67 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:     0x55bd3181d7fc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55bd3181eb82 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x55bd312dc8e3 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x55bd312dcba3 - core::result::unwrap_failed::ha17dbf463031a5e1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
  16:     0x55bd312e0565 - core::result::Result<T,E>::unwrap::hc76bc8ef087a958f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
  17:     0x55bd312e7beb - color_scheme::main::{{closure}}::h676b74a31767720a
                               at /home/eduardo/Developer/GitHub/edfloreshz/rust-dark-light/examples/color_scheme.rs:5:24
  18:     0x55bd312e718c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9c10be68a6c43cf0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  19:     0x55bd312e9b50 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::ha9c0fb5922d248b9
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:63
  20:     0x55bd312e9959 - tokio::runtime::coop::with_budget::h374a6eb4c304d124
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:102:5
  21:     0x55bd312e9959 - tokio::runtime::coop::budget::hb7696c2b75afcb45
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:68:5
  22:     0x55bd312e9959 - tokio::runtime::park::CachedParkThread::block_on::h881e06b99f70fb52
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:31
  23:     0x55bd312e82f5 - tokio::runtime::context::BlockingRegionGuard::block_on::h08783a21d0edfcfe
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/context.rs:295:13
  24:     0x55bd312e9fd5 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h3159921632df782c
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  25:     0x55bd312eb449 - tokio::runtime::runtime::Runtime::block_on::h084150448d13be7b
                               at /home/eduardo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/runtime.rs:284:45
  26:     0x55bd312ea1a7 - color_scheme::main::h9b8b51354d52e12e
                               at /home/eduardo/Developer/GitHub/edfloreshz/rust-dark-light/examples/color_scheme.rs:6:5
  27:     0x55bd312df37b - core::ops::function::FnOnce::call_once::hf3dbfc3dd1633528
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  28:     0x55bd312e454e - std::sys_common::backtrace::__rust_begin_short_backtrace::h93f5f078ce0a1b23
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  29:     0x55bd312e8871 - std::rt::lang_start::{{closure}}::h6b8a395c99773c0f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:166:18
  30:     0x55bd3181432b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h072eb4cd8da964ba
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286:13
  31:     0x55bd3181432b - std::panicking::try::do_call::h8eca204fe9266946
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  32:     0x55bd3181432b - std::panicking::try::h12574e1b7b2cbacb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  33:     0x55bd3181432b - std::panic::catch_unwind::hf71522d4448329d6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  34:     0x55bd3181432b - std::rt::lang_start_internal::{{closure}}::h65b66ac9bff580f8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:48
  35:     0x55bd3181432b - std::panicking::try::do_call::hfff61e33ca3db9f1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  36:     0x55bd3181432b - std::panicking::try::he48c8ecead279cad
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  37:     0x55bd3181432b - std::panic::catch_unwind::hd510a26bfc950ccc
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  38:     0x55bd3181432b - std::rt::lang_start_internal::hc680b25eab888da9
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:20
  39:     0x55bd312e884a - std::rt::lang_start::hd05f42c2454c1d0c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:165:17
  40:     0x55bd312ea25e - main
  41:     0x7f1363629d90 - <unknown>
  42:     0x7f1363629e40 - __libc_start_main
  43:     0x55bd312dcd85 - _start
  44:                0x0 - <unknown>
```

**Comment by A6GibKm** [comment]
Could you please post a backtrace so I can look into it tomorrow?

**Comment by edfloreshz** [comment]
Issue description updated with backtrace, thanks!

**Comment by edfloreshz** [comment]
You can run the code from this [repo](https://github.com/edfloreshz/rust-dark-light/tree/callback) using `cargo run --example color_scheme`

**Comment by bilelmoussaoui** [comment]
I found the issue, somehow zbus gives us a `OwnedValue(Value($the_actual_type))` instead of `OwnedValue($the_actual_type)`. I am going to open an issue on zbus side and workaround it on ashpd for now

**Comment by A6GibKm** [comment]
And I found out that xdp actually returns `Value(Value(u))` instead of `Value(u)`.

**Comment by bilelmoussaoui** [comment]
Should be fixed with https://github.com/bilelmoussaoui/ashpd/pull/107

**Comment by edfloreshz** [comment]
Thanks! 🎉
